module.exports = {
    "fr": {
        helptitle: "Liste des commandes",
        setlangerror: "\`•\` La langue que vous avez défini n'est pas encore disponible ! \`Erreur 1\`.",
        helpsetlang: "Permet de définir la langue du bot",
        isAdministrator: "est un **administrateur** du serveur !",
        notAdministrator: "n'est pas un **administrateur** du serveur !",
        listadministrator: "Liste des administrateurs",
        isBan: "est un **banni** du serveur !",
        isNotBan: "n'est pas un **banni** du serveur !",
        listbans: "Liste des bannis",
        nobans: "*Aucun Bannis*",
        isrobot: "est un **robot** du serveur !",
        isnotrobot: "n'est pas un **robot** du serveur !",
        listbot: "Liste des Bots",
        listchannels: "Liste des salons",
        listroles: "Liste des rôles",
        banner: "Bannière de",
        nobanner: "L'utilisateur que vous avez indiqué n'a pas de bannière !",
        isBooster: "est un **booster** du serveur !",
        isNotBooster: "n'est pas un **booster** du serveur !",
        nobooster: "Le serveur n'a aucun boost.",
        listboost: "Liste des boosters",
        textchannel: "Salon Textuel",
        privatemsg: "Message privée",
        vocalchannel: "Salon Vocaux",
        category: "Catégorie",
        announcechannel: "Salon d'annonce",
        filsnew: "Fils de nouveauté",
        filspublic: "Fils Publique",
        filsprivate: "Fils Privé",
        stage: "Stage",
        media: "Média",
        name: "Nom",
        channelInfoguild: "Information du salon sur",
        channelInfo: "Information sur le salon",
        user: "Utilisateurs",
        advancedInformation: "Informations avancées",
        modelent: "Mode lent",
        yes: "Oui",
        no: "Non",
        desactivate: "Désactivé",
        noprocessor: "Nom du processeur non disponible",
        errorprocessor: "Erreur lors de la récupération du nom du processeur:",
        inviteme: "Invite Moi",
        informationof: "Information sur",
        username: "Nom d'utilisateur",
        pic: "Avatar de",
        download: "Télécharger",
        ping: "\`•\` Mon ping est de: ",
        help1: "\`•\` Bienvenue sur le menu d'aide du bot !\n[WhiteHall](https://discord.com/api/oauth2/authorize?client_id=1128625929523036160&permissions=8&scope=bot%20applications.commands) est un bot multifonction et gratuit ! Cependant il est disponible une version payante **ENTIÈREMENT CUSTOMISABLE** pour 2€50. N'hésite pas à rejoindre le serveur pour en savoir plus https://discord.gg/JkduXanB8r !\n\n\`•\` Mon préfix est le suivant: ",
        help2: "\n\`•\` Si tu trouves un bug n'hésite pas à faire la commande",
        help3: "\n\n\`•\` Au passage `[...]` signifie `obligatoire`, `(...)` signifie `facultatif` et `{...}` signifie `option` !",
        help4: "\n\n\`•\` A l'aide du gif ci-dessous choisissez le menu d'aide du bot:",
        home: "Accueil",
        generalinformation: "Information général",
        utils: "Outils",
        helpdescription: "Permet de voir la liste des commandes avec leurs descriptions",
        botinfodescription: "Permet de voir les information du bot",
        pingdescription: "Permet de voir la latence du bot",
        alladminsdescription: "Permet de voir la liste des admins sur le serveur.",
        allbansdescription: "Permet de voir la liste des bannis sur le serveur.",
        allboostersdescription: "Permet de voir la liste des boosters sur le serveur.",
        allbotsdescription: "Permet de voir la liste des bots sur le serveur.",
        allchannelsdescription: "Permet de voir la liste des salons sur le serveur.",
        allrolesdescription: "Permet de voir la liste des rôles sur le serveur.",
        bannerdescription: "Permet de voir la bannière d'un utilisateur.",
        channelinfodescription: "Permet de voir les informations d'un salon.",
        picdescription: "Permet de voir l'avatar d'un utilisateur.",
        anyuser: "*Aucun utilisateurs*",
        listofuser: "Liste des utilisateurs",
        rolememberdescription: "Permet de voir la liste de tous les utilisateurs appartenant à un rôle.",

        cherchuser: "\`•\` Veuillez indiquer un utilisateur sûr le serveur !",
        dontauthorize: "\`•\` Tu n'es pas autorisé à interagir sur ces boutons !",
        anyrole: " Veuillez indiquer un rôle valide !",

        gifhelpmenu: "https://media.discordapp.net/attachments/1170288145871413318/1211775227185598595/gifhelpfr.gif?ex=65ef6c9f&is=65dcf79f&hm=420a6788a02fed7a7063688310820c72aedefc6f3399399d76307f8c6ddc4939&=&width=1200&height=656"
    },
    "en": {
        helptitle: "List of commands",
        setlangerror: "\`•\` The language you defined is not yet available ! \`Error 1\`.",
        helpsetlang: "Allows you to set the bot language.",
        isAdministrator: "is an **administrator** of the server !",
        notAdministrator: "is not an **administrator** of the server!",
        listadministrator: "List of administrators",
        isBan: "is **banned** from the server!",
        isNotBan: "is not **banned** from the server!",
        listbans: "Banned list",
        nobans: "*No Bans*",
        isrobot: "is a **bot** of the server!",
        isnotrobot: "is not a **bot** of the server!",
        listbot: "List of Bots",
        listchannels: "List of channels",
        listroles: "Liste of role",
        banner: "Banner of",
        nobanner: "The user you specified does not have a banner !",
        isBooster: "is a **booster** of the server!",
        isNotBooster: "is not a server **booster**!",
        nobooster: "The server has no boost.",
        listboost: "Liste of boosters",
        textchannel: "Textual Channel",
        privatemsg: "Private message",
        vocalchannel: "Vocal channel",
        category: "Category",
        announcechannel: "Announce channel",
        filsnew: "Novelty thread",
        filspublic: "Public thread",
        filsprivate: "Private Thread",
        stage: "Stage",
        media: "Media",
        name: "Name",
        channelInfoguild: "Channel information about",
        channelInfo: "Information Channel of",
        user: "Users",
        advancedInformation: "Advanced Information",
        modelent: "Slow mode",
        yes: "Yes",
        no: "No",
        desactivate: "Desactivate",
        noprocessor: "Processor name not available",
        errorprocessor: "Error retrieving processor name:",
        inviteme: "Invite Me",
        informationof: "Information of",
        username: "Username",
        pic: "Avatar of",
        download: "Download",
        ping: "\`•\` My latency is: ",
        help1: "\`•\` Welcome to the bot help menu!\n[WhiteHall](https://discord.com/api/oauth2/authorize?client_id=1128625929523036160&permissions=8&scope=bot%20applications.commands) is a bot multifunctional and free! However, a paid version **FULLY CUSTOMIZABLE** is available for €2.50. Don't hesitate to join the server to find out more https://discord.gg/JkduXanB8r !\n\n\`•\` My prefix is as follows:",
        help2: "\n\`•\` If you find a bug don't hesitate to command this",
        help3: "\n\n\`•\` By the way `[...]` means `obligatory`, `(...)` means `optional` and `{...}` means `option`!",
        help4: "\n\n\`•\` Using the gif below choose the bot's help menu:",
        home: "Home",
        generalinformation: "General Information",
        utils: "Utils",
        helpdescription: "Allows you to see the list of commands with their descriptions",
        botinfodescription: "Allows you to see the bot's information",
        pingdescription: "Allows you to see the bot latency",
        alladminsdescription: "Allows you to see the list of admins on the server.",
        allbansdescription: "Allows you to see the list of banned people on the server.",
        allboostersdescription: "Allows you to see the list of boosters on the server.",
        allbotsdescription: "Allows you to see the list of bots on the server.",
        allchannelsdescription: "Allows you to see the list of channels on the server.",
        allrolesdescription: "Allows you to see the list of roles on the server.",
        bannerdescription: "Allows you to see a user's banner.",
        channelinfodescription: "Allows you to see information about a channel.",
        picdescription: "Allows you to see a user's avatar.",
        anyuser: "*No users*",
        listofuser: "List of users",
        rolememberdescription: "Allows you to see the list of all users belonging to a role.",

        cherchuser: "\`•\` Please specify a safe user on the server !",
        dontauthorize: "\`•\` You are not allowed to interact with these buttons !",
        anyrole: "Please enter a valid role!",

        gifhelpmenu: "https://media.discordapp.net/attachments/1170288145871413318/1211774298667352084/gifhelpen.gif?ex=65ef6bc2&is=65dcf6c2&hm=f3a432f9c30eba2c260c71a374b33feec6b1480cb011e4be4e4b28f0a675499d&=&width=1200&height=656"
    }
}

Dernière modification: 28 février 2024 18:43
